apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: instructlab
resources:
  - namespace.yaml
  - ui
  - doclingserve
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: ui
