apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclingserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doclingserve
  template:
    metadata:
      labels:
        app: doclingserve
    spec:
      containers:
      - name: doclingserve
        image: quay.io/ds4sd/docling-serve:latest
        ports:
        - containerPort: 5001
          hostPort: 5001
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: quay.io/instructlab-ui/ui:latest
        env:
        - name: IL_UI_DEPLOYMENT
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: IL_UI_DEPLOYMENT
        - name: OAUTH_GITHUB_ID
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: OAUTH_GITHUB_ID
        - name: OAUTH_GITHUB_SECRET
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: OAUTH_GITHUB_SECRET
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: GITHUB_TOKEN
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: NEXTAUTH_SECRET
        - name: NEXTAUTH_URL
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: NEXTAUTH_URL
        - name: NEXT_PUBLIC_AUTHENTICATION_ORG
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: NEXT_PUBLIC_AUTHENTICATION_ORG
        - name: NEXT_PUBLIC_TAXONOMY_REPO
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: NEXT_PUBLIC_TAXONOMY_REPO
        - name: NEXT_PUBLIC_TAXONOMY_REPO_OWNER
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: NEXT_PUBLIC_TAXONOMY_REPO_OWNER
        - name:  NEXT_PUBLIC_TAXONOMY_DOCUMENTS_REPO
          valueFrom:
            secretKeyRef:
              name: ui-env
              key:  NEXT_PUBLIC_TAXONOMY_DOCUMENTS_REPO
        - name: NEXT_PUBLIC_EXPERIMENTAL_FEATURES
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: NEXT_PUBLIC_EXPERIMENTAL_FEATURES
        - name: IL_GRANITE_API
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: IL_GRANITE_API
        - name: IL_GRANITE_MODEL_NAME
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: IL_GRANITE_MODEL_NAME
        - name: IL_MERLINITE_API
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: IL_MERLINITE_API
        - name: IL_MERLINITE_MODEL_NAME
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: IL_MERLINITE_MODEL_NAME
        - name: IL_ENABLE_DEV_MODE
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: IL_ENABLE_DEV_MODE
        ports:
        - containerPort: 3000
          hostPort: 3000
        imagePullPolicy: Always
